apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: your-progress
  name: your-progress
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: your-progress
  template:
    metadata:
      labels:
        app: your-progress
    spec:
      containers:
      - name: your-progress
        image: 10.0.0.200:5000/progress:0.0.1-arm
        imagePullPolicy: Always
        env:
        - name: APP_TYPE
          value: 'STAGE'
        - name: PYTHONDONTWRITEBYTECODE
          value: '1'
        - name: PYTHONUNBUFFERED
          value: '1'
        - name: PYTHONASYNCIODEBUG
          value: '1'
        - name: DEBUG_MODE
          value: '1'
        - name: ALLOWED_HOSTS
          value: '*'
        resources:
          limits:
            memory: '2000Mi'
          requests:
            memory: '2000Mi'
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            #path: /api/v1/healthcheck
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            #path: /api/v1/healthcheck
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
      restartPolicy: Always
